#!/bin/bash
for VERSION in $(grep -v '^$' versions.txt | xargs)
do
    # PHP build
    echo "Building digbang/php:${VERSION}..."
    mkdir -p php/$VERSION
    cp -r templates/php/* php/$VERSION
    sed -ri -e 's/%%VERSION%%/'"$VERSION"'/' php/$VERSION/Dockerfile

    # PHP-DEV build
    echo "Building digbang/php-dev:${VERSION}..."
    mkdir -p php-dev/$VERSION
    cp -r templates/php-dev/* php-dev/$VERSION
    sed -ri -e 's/%%VERSION%%/'"$VERSION"'/' php-dev/$VERSION/Dockerfile
done
