#!/bin/bash
for VERSION in 7.4 8.1 8.2-apache
do
    echo "Building digbang/php:${VERSION}"

    mkdir -p php/$VERSION
    cp php/Dockerfile_$VERSION.template php/$VERSION/Dockerfile
    sed -ri -e 's/%%VERSION%%/'"$VERSION"'/' php/$VERSION/Dockerfile

    echo "Building digbang/php-dev:${VERSION}"

    mkdir -p php-dev/$VERSION
    cp php-dev/Dockerfile.template php-dev/$VERSION/Dockerfile
    sed -ri -e 's/%%VERSION%%/'"$VERSION"'/' php-dev/$VERSION/Dockerfile
done
