#!/bin/bash
VERSIONS=(5.6 7.0 7.1)
LATEST=7.1

for VERSION in $VERSIONS
do
    echo "Building digbang/php:${VERSION}"

    mkdir -p $VERSION
    cp Dockerfile.template $VERSION/Dockerfile
    cd $VERSION
    sed -ri -e 's/%%VERSION%%/'"$VERSION"'/' Dockerfile
    
    if [ "$VERSION" == "$LATEST" ]
    then
        docker build -t digbang/php:${VERSION} -t digbang/php:latest .
    else
        docker build -t digbang/php:${VERSION} .
    fi
done

echo "Pushing to Docker registry"
docker push digbang/php
